id: P009489
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG4190
  title: ཕྱག་ཆེན་ལྷན་སྐྱེས་ཀྱི་དངོས་གཞིའི་ཁྲིད་ཡིག་
  author: ''
  volumes:
    1133a7a808f24e51bb7da5ca73d36c31:
      image_group_id: I1PD96697
      title: ''
      volume_number: 1
      total_pages: 682
      base_file: v001.txt
