id: I7593331A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T09:25:31+00:00'
last_modified: '2022-06-08T11:23:46.569081+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4190
  title: ཕྱག་ཆེན་ལྷན་སྐྱེས་ཀྱི་དངོས་གཞིའི་ཁྲིད་ཡིག་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '5952':
      image_group_id: I1PD96697
      title: ''
      total_pages: 682
      order: 1
      base_file: 5952.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
