id: I7593331A
legacy_id: P009489
ocr_import_info:
  bdrc_scan_id: W1KG4190
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T09:21:09'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T15:22:48.558245+00:00'
last_modified: 2022-08-31 23:23:07.592257
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4190
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4190
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཕྱག་ཆེན་ལྷན་སྐྱེས་ཀྱི་དངོས་གཞིའི་ཁྲིད་ཡིག
  author: ཁམས་སྤྲུལ ༠༣་ཀུན་དགའ་བསྟན་འཛིན།
statistics:
  ocr_word_mean_confidence_index: 0.7490291031439484
  ocr_word_median_confidence_index: 0.800000011920929
quality: null
bases:
  I1PD96697:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD96697
      total_pages: 682
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD96697.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.7490291031439484
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
